server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
logging:
  level:
    root: "INFO"
    web: "TRACE"

spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
        routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/order/**

          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/v1/inventory/**

          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/product/**

          - id: eureka-server
            uri: http://localhost:8080
            predicates:
              - Path=/eureka/web/**
            filters:
              - SetPath=/

          - id: eureka-server-static
            uri: http://localhost:8080
            predicates:
              - Path=/eureka/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8087/realms/ecom_service_realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8087/realms/ecom_service_realm

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0
