server:
  port: 8083
spring:
  application:
    name: product-service
  data:
        mongodb:
          uri: mongodb://localhost:27017/product-service

  autoconfigure:
     exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}