server:
  port: 0
spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
        hibernate:
          dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/order-service"
    username: "user"
    password: "password"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
app:
  property:
    inventory:
      service-url: "http://inventory-service/api/v1/inventory/list"
