server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
        hibernate:
          dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/order-service"
    username: "user"
    password: "password"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
app:
  property:
    inventory:
      service-url: "http://localhost:8082/api/v1/inventory/list"