server:
  port: 8082
spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3307/inventory-service"
    username: "user"
    password: "password"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0