server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3307/inventory-service"
    username: "user"
    password: "password"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
